accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'job'

urlpatterns = [
    path('signup',views.signup, name='signup'),
    path('profile',views.profile, name='profile'),
    path('profile_edit',views.profile_edit, name='profile_edit'),
]

job/urls.py
from django.urls import path, include
from . import views
from . import api


app_name = 'job'

urlpatterns = [
    path('',views.job_list, name='job_list'),
    path('add_jop', views.add_jop, name='add_jop'),
    path('<str:slug>',views.job_detailes, name='job_detail'),

    # api
    path('api/list', api.joblistapi, name='joblistapi'),
    path('api/list/<int:id>', api.job_detailes_api, name='job_detailes_api'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('job.urls', namespace='jobs')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls', namespace='jobs')),
    path('contact-us/',include('contact.urls', namespace='contact')),
    path('api-auth/', include('rest_framework.urls'))

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.ForeignKey('City' , related_name='user_city', on_delete=models.CASCADE , blank=True , null=True)
    phone_number = models.CharField(max_length=15)
    image  = models.ImageField(upload_to='profile/')

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

class City(models.Model):
    name = models.CharField(max_length= 30)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields =  'username', 'email', 'password1', 'password2'

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
    

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city','phone_number','image']

accounts/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from django.urls import reverse
from .forms import SignupForm, UserForm, ProfileForm
from .models import Profile

# Create your views here.


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username = username, password = password)
            login(request, user)
            return redirect('/accounts/profile')

    else:
        form = SignupForm()

    return render(request, 'registration/signup.html', {'form':form})



def profile(request):
    profile = Profile.objects.get(user = request.user)
    return render(request, 'accounts/profile.html', {'profile':profile})



def profile_edit(request):
    profile = Profile.objects.get(user = request.user)
    

    if request.method == 'POST':
        profile_form = ProfileForm(request.POST,request.FILES,instance=profile)
        user_form = UserForm(request.POST,instance=request.user)
        if profile_form.is_valid() and user_form.is_valid():
            user_form.save()
            new_profile = profile_form.save(commit=False)
            new_profile.user = request.user
            new_profile.save() 
            return redirect( reverse('accounts:profile')   )


            pass

    else:
        profile_form = ProfileForm(instance=profile)
        user_form = UserForm(instance=request.user)

    context = {
        'profile_form':profile_form,
        'user_form':user_form
    }
    return render(request, 'accounts/profile_edit.html',context)

accounts/templates/accounts/profile.html
{% extends 'base.html' %} 
{% load bootstrap4 %} 
{% load static %} 
{% block body%}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>{{job_detailes.title}}</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <div class="job_sumary">
          <div class="summery_header">
            <h3>Profile</h3>
          </div>
          <div class="job_content">
            <ul>
              <li>name: <span>{{profile.user}}</span></li>
              <li>email: <span>{{profile.user.email}}</span></li>
              <li>city: <span>{{profile.city}}</span></li>
              <li>Phone Number: <span>{{profile.phone_number}}</span></li>
            </ul>
          </div>
          <div class="m-5 boxed-btn3"> 
            <a href="{% url 'accounts:profile_edit' %}">Edit Profile</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

<div class="submit_btn"></div>

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %} 
{% load bootstrap4 %} 
{% load static %} 
{% block body%}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>{{job_detailes.title}}</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
  <div class="container">
    <div class="row">
      <div class="col-lg-10 mx-auto">
        <div class="apply_job_form white-bg">
          <h4>Add mew job</h4>


          <form action="#" method="POST" enctype="multipart/form-data">
            {% csrf_token %} 
            {% bootstrap_form user_form %} 
            {% bootstrap_form profile_form %} 
            {% buttons %}
            <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
            {% endbuttons %}
          </form>

        </div>
      </div>
      <div class="col-lg-4">
        <div class="job_location_wrap">
          <div class="job_lok_inner">
            <div id="map" style="height: 200px"></div>
            <script>
              function initMap() {
                var uluru = { lat: -25.363, lng: 131.044 };
                var grayStyles = [
                  {
                    featureType: "all",
                    stylers: [{ saturation: -90 }, { lightness: 50 }],
                  },
                  {
                    elementType: "labels.text.fill",
                    stylers: [{ color: "#ccdee9" }],
                  },
                ];
                var map = new google.maps.Map(document.getElementById("map"), {
                  center: { lat: -31.197, lng: 150.744 },
                  zoom: 9,
                  styles: grayStyles,
                  scrollwheel: false,
                });
              }
            </script>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}